# generated by datamodel-codegen:
#   filename:  genesys.schema.json
#   timestamp: 2026-08-21T08:27:01+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, conint


class Characteristics(BaseModel):
    brawn: conint(ge=1, le=6)
    agility: conint(ge=1, le=6)
    intellect: conint(ge=1, le=6)
    cunning: conint(ge=1, le=6)
    willpower: conint(ge=1, le=6)
    presence: conint(ge=1, le=6)


class Wounds(BaseModel):
    threshold: conint(ge=0)
    current: conint(ge=0)


class Strain(BaseModel):
    threshold: conint(ge=0)
    current: conint(ge=0)


class Defense(BaseModel):
    melee: conint(ge=0)
    ranged: conint(ge=0)


class DerivedAttributes(BaseModel):
    soak_value: conint(ge=0)
    wounds: Wounds
    strain: Strain
    defense: Defense


class CriticalInjury(BaseModel):
    name: str
    severity_diamonds: conint(ge=1, le=4)
    effect: str
    duration: str


class Characteristic(Enum):
    brawn = 'brawn'
    agility = 'agility'
    intellect = 'intellect'
    cunning = 'cunning'
    willpower = 'willpower'
    presence = 'presence'


class Skill(BaseModel):
    name: str
    characteristic: Characteristic
    rank: conint(ge=0, le=5)
    career: bool
    setting_specific: bool
    description: str | None = None


class Type(Enum):
    talent = 'talent'
    ability = 'ability'


class TalentsAndAbility(BaseModel):
    name: str
    type: Type
    tier: conint(ge=0, le=5) | None = None
    description: str
    reference_page: str | None = None


class Range(Enum):
    Engaged = 'Engaged'
    Short = 'Short'
    Medium = 'Medium'
    Long = 'Long'
    Extreme = 'Extreme'


class Weapon(BaseModel):
    name: str
    skill: str
    damage: conint(ge=0)
    critical: conint(ge=1)
    range: Range
    special: list[str] | None = None
    reference_page: str | None = None


class InventoryItem(BaseModel):
    name: str
    quantity: conint(ge=1)
    encumbrance: conint(ge=0)


class Experience(BaseModel):
    total: conint(ge=0)
    available: conint(ge=0)


class MotivationObject(BaseModel):
    name: str
    description: str


class RelationshipObject(BaseModel):
    entity_name: str
    relationship_type: str
    description: str


class Motivations(BaseModel):
    strength: MotivationObject | None = None
    flaw: MotivationObject | None = None
    desire: MotivationObject | None = None
    fear: MotivationObject | None = None


class NarrativeProfile(BaseModel):
    physical_description: str | None = None
    backstory: str | None = None
    motivations: Motivations | None = None
    bonds_and_rivalries: list[RelationshipObject] | None = None


class GenesysCharacterSheet(BaseModel):
    character_name: str
    player_name: str | None = None
    archetype: str | None = None
    career: str | None = None
    characteristics: Characteristics
    derived_attributes: DerivedAttributes
    critical_injuries: list[CriticalInjury] | None = None
    skills: list[Skill]
    talents_and_abilities: list[TalentsAndAbility] | None = None
    weapons: list[Weapon] | None = None
    inventory: list[InventoryItem] | None = None
    experience: Experience | None = None
    narrative_profile: NarrativeProfile | None = None
